/*
 * leg_function.c
 *
 *  Created on: Dec 10, 2024
 *      Author: YI MING
 */
#include <math.h>
#include "board_lib.h"
#include "bsp_imu.h"
#include "robot_config.h"
#include "dm4310_drv.h"
#include "leg_task.h"
#include "rt_nonfinite.h"
#include "rt_defines.h"

LegPos leftLegPos, rightLegPos;
extern Motor leftJoint[2], rightJoint[2], leftWheel, rightWheel;

void leg_task(void *argument) {
	float legPos[2], legSpd[2];
	const float lpfRatio = 0.5f; //低通滤波系数(新值的权重)
	float lastLeftDLength = 0, lastRightDLength = 0;
    while (1) {

    	leg_pos(leftJoint[0].angle, leftJoint[1].angle, legPos);
    	leftLegPos.length = legPos[0];
    	leftLegPos.angle = legPos[1];
    	leg_spd(leftJoint[0].speed, leftJoint[1].speed, leftJoint[0].angle, leftJoint[1].angle, legSpd);
    	leftLegPos.dLength = legSpd[0];
    	leftLegPos.dAngle = legSpd[1];
    	leftLegPos.ddLength = ((leftLegPos.dLength - lastLeftDLength) * 1000 / 5) * lpfRatio + leftLegPos.ddLength * (1 - lpfRatio);
    	lastLeftDLength = leftLegPos.dLength;
    	leg_pos(rightJoint[0].angle, rightJoint[1].angle, legPos);
    	rightLegPos.length = legPos[0];
    	rightLegPos.angle = legPos[1];
    	leg_spd(rightJoint[0].speed, rightJoint[1].speed, rightJoint[0].angle, rightJoint[1].angle, legSpd);
    	rightLegPos.dLength = legSpd[0];
    	rightLegPos.dAngle = legSpd[1];
    	rightLegPos.ddLength = ((rightLegPos.dLength - lastRightDLength) * 1000 / 5) * lpfRatio + rightLegPos.ddLength * (1 - lpfRatio);
    	lastRightDLength = rightLegPos.dLength;
    	vTaskDelay(5);
    }
}


/* Function Declarations */
static double rt_atan2d_snf(double u0, double u1);

/* Function Definitions */
/*
 * Arguments    : double u0
 *                double u1
 * Return Type  : double
 */
static double rt_atan2d_snf(double u0, double u1)
{
  double y;
  if (rtIsNaN(u0) || rtIsNaN(u1)) {
    y = rtNaN;
  } else if (rtIsInf(u0) && rtIsInf(u1)) {
    int i;
    int i1;
    if (u0 > 0.0) {
      i = 1;
    } else {
      i = -1;
    }
    if (u1 > 0.0) {
      i1 = 1;
    } else {
      i1 = -1;
    }
    y = atan2(i, i1);
  } else if (u1 == 0.0) {
    if (u0 > 0.0) {
      y = RT_PI / 2.0;
    } else if (u0 < 0.0) {
      y = -(RT_PI / 2.0);
    } else {
      y = 0.0;
    }
  } else {
    y = atan2(u0, u1);
  }
  return y;
}

void leg_pos(float phi1, float phi4, float pos[2])
{
	float a;
	float b_a;
	float t14;
	float t15;
	float t2;
	float t3;
	float t4;
	float t5;
	float t6;
	float t8;
  /*     This function was generated by the Symbolic Math Toolbox version 24.1.
   */
  /*     10-Dec-2024 12:58:30 */
  t2 = cos(phi1);
  t3 = cos(phi4);
  t4 = sin(phi1);
  t5 = sin(phi4);
  t6 = t2 * 0.15;
  t8 = t4 * 0.15;
  t14 = t4 * 0.084;
  t15 = t5 * 0.084;
  t5 = t8 - t5 * 0.15;
  a = (t3 * 0.15 - t6) + 0.15;
  b_a = t14 - t15;
  t4 = (t3 * 0.084 - t2 * 0.084) + 0.084;
  t5 = t5 * t5 + a * a;
  t4 = atan(1.0 / (t4 + t5) *
            ((t15 - t14) + sqrt((b_a * b_a + t4 * t4) - t5 * t5))) *
       2.0;
  t5 = t8 + sin(t4) * 0.28;
  t4 = (t6 + cos(t4) * 0.28) - 0.075;
  pos[0] = sqrt(t5 * t5 + t4 * t4);
  pos[1] = rt_atan2d_snf(t5, t4);
}
void leg_conv(float F, float Tp, float phi1, float phi4, float T[2])
{
	float t100;
  float t102_tmp;
  float t108_tmp;
  float t120_tmp;
  float t123_tmp;
  float t124_tmp;
  float t131_tmp;
  float t16_tmp;
  float t174;
  float t175;
  float t18_tmp;
  float t30_tmp;
  float t31_tmp;
  float t32_tmp;
  float t33_tmp;
  float t51_tmp;
  float t52_tmp;
  float t5_tmp;
  float t62_tmp;
  float t77_tmp;
  float t7_tmp;
  float t81_tmp;
  float t82_tmp;
  float t91_tmp;
  /*     This function was generated by the Symbolic Math Toolbox version 24.1.
   */
  /*     10-Dec-2024 12:58:31 */
  t174 = cos(phi1);
  t5_tmp = cos(phi4);
  t175 = sin(phi1);
  t7_tmp = sin(phi4);
  t16_tmp = t174 * 0.15;
  t18_tmp = t175 * 0.15;
  t30_tmp = t174 * 0.084;
  t31_tmp = t5_tmp * 0.084;
  t32_tmp = t175 * 0.084;
  t33_tmp = t7_tmp * 0.084;
  t100 = t18_tmp - t7_tmp * 0.15;
  t51_tmp = (t5_tmp * 0.15 - t16_tmp) + 0.15;
  t52_tmp = t32_tmp - t33_tmp;
  t62_tmp = (t31_tmp - t30_tmp) + 0.084;
  t77_tmp = t100 * t100 + t51_tmp * t51_tmp;
  t81_tmp = t174 * t100 * 0.3 + t175 * t51_tmp * 0.3;
  t82_tmp = t5_tmp * t100 * 0.3 + t7_tmp * t51_tmp * 0.3;
  t51_tmp = 1.0 / (t62_tmp + t77_tmp);
  t91_tmp = t51_tmp * t51_tmp;
  t100 = sqrt((t52_tmp * t52_tmp + t62_tmp * t62_tmp) - t77_tmp * t77_tmp);
  t102_tmp = 1.0 / t100;
  t108_tmp = (t33_tmp - t32_tmp) + t100;
  t120_tmp = atan(t51_tmp * t108_tmp) * 2.0;
  t123_tmp = cos(t120_tmp);
  t124_tmp = sin(t120_tmp);
  t131_tmp = 1.0 / (t91_tmp * (t108_tmp * t108_tmp) + 1.0);
  t120_tmp = (t32_tmp + t81_tmp) * t91_tmp * t108_tmp +
             t51_tmp * (t30_tmp -
                        t102_tmp *
                            ((t174 * t52_tmp * 0.168 + t175 * t62_tmp * 0.168) -
                             t77_tmp * t81_tmp * 2.0) /
                            2.0);
  t30_tmp =
      (t33_tmp + t82_tmp) * t91_tmp * t108_tmp +
      t51_tmp * (t31_tmp -
                 t102_tmp *
                     ((t5_tmp * t52_tmp * 0.168 + t7_tmp * t62_tmp * 0.168) -
                      t77_tmp * t82_tmp * 2.0) /
                     2.0);
  t32_tmp = t18_tmp + t124_tmp * 0.28;
  t81_tmp = (t16_tmp + t123_tmp * 0.28) - 0.075;
  t100 = (-t16_tmp - t123_tmp * 0.28) + 0.075;
  t174 = t100 * t100;
  t175 = 1.0 / t100;
  t100 = t32_tmp * t32_tmp;
  t102_tmp = t123_tmp * t131_tmp;
  t91_tmp = t16_tmp - t102_tmp * t120_tmp * 0.56;
  t82_tmp = t124_tmp * t131_tmp;
  t120_tmp = t18_tmp - t82_tmp * t120_tmp * 0.56;
  t108_tmp = F * (1.0 / sqrt(t100 + t81_tmp * t81_tmp));
  t51_tmp = Tp * t174 * (1.0 / (t100 + t174));
  t100 = t32_tmp * (1.0 / t174);
  T[0] = t108_tmp * (t32_tmp * t91_tmp * 2.0 - t81_tmp * t120_tmp * 2.0) / 2.0 -
         t51_tmp * (t175 * t91_tmp - t100 * t120_tmp);
  T[1] = t108_tmp *
             (t102_tmp * t32_tmp * t30_tmp * 1.12 -
              t82_tmp * t81_tmp * t30_tmp * 1.12) /
             2.0 +
         t51_tmp * (t175 * (0.0 - t102_tmp * t30_tmp * 0.56) +
                    t100 * (t82_tmp * t30_tmp * 0.56));
}

void leg_spd(float dphi1, float dphi4, float phi1, float phi4,
             float spd[2])
{
  float t10_tmp;
  float t12_tmp;
  float t2;
  float t20;
  float t21;
  float t22;
  float t23;
  float t28;
  float t3;
  float t30;
  float t31;
  float t36;
  float t4;
  float t44;
  float t47;
  float t48;
  float t5;
  float t52;
  float t53;
  float t59;
  float t60;
  float t70;
  float t71;
  float t76;
  /*     This function was generated by the Symbolic Math Toolbox version 24.1.
   */
  /*     10-Dec-2024 12:58:30 */
  t2 = cos(phi1);
  t3 = cos(phi4);
  t4 = sin(phi1);
  t5 = sin(phi4);
  t10_tmp = t2 * 0.15;
  t12_tmp = t4 * 0.15;
  t20 = t2 * 0.084;
  t21 = t3 * 0.084;
  t22 = t4 * 0.084;
  t23 = t5 * 0.084;
  t28 = t12_tmp - t5 * 0.15;
  t30 = (t3 * 0.15 - t10_tmp) + 0.15;
  t31 = t22 - t23;
  t36 = (t21 - t20) + 0.084;
  t44 = t28 * t28 + t30 * t30;
  t47 = t2 * t28 * 0.3 + t4 * t30 * 0.3;
  t48 = t3 * t28 * 0.3 + t5 * t30 * 0.3;
  t52 = 1.0 / (t36 + t44);
  t53 = t52 * t52;
  t59 = sqrt((t31 * t31 + t36 * t36) - t44 * t44);
  t60 = 1.0 / t59;
  t30 = (t23 - t22) + t59;
  t28 = atan(t52 * t30) * 2.0;
  t70 = cos(t28);
  t71 = sin(t28);
  t76 = 1.0 / (t53 * (t30 * t30) + 1.0);
  t47 = (t22 + t47) * t53 * t30 +
        t52 * (t20 -
               t60 * ((t2 * t31 * 0.168 + t4 * t36 * 0.168) - t44 * t47 * 2.0) /
                   2.0);
  t28 = (t23 + t48) * t53 * t30 +
        t52 * (t21 -
               t60 * ((t3 * t31 * 0.168 + t5 * t36 * 0.168) - t44 * t48 * 2.0) /
                   2.0);
  t4 = t12_tmp + t71 * 0.28;
  t20 = (t10_tmp + t70 * 0.28) - 0.075;
  t59 = t70 * t76;
  t22 = t59 * t28;
  t53 = t71 * t76;
  t2 = t53 * t28;
  t28 = (-t10_tmp - t70 * 0.28) + 0.075;
  t60 = t28 * t28;
  t52 = 1.0 / t28;
  t30 = t4 * t4;
  t28 = 1.0 / sqrt(t30 + t20 * t20);
  t48 = 1.0 / (t30 + t60);
  t59 = t10_tmp - t59 * t47 * 0.56;
  t30 = t12_tmp - t53 * t47 * 0.56;
  spd[0] = dphi4 * t28 * (t4 * t22 * 1.12 - t20 * t2 * 1.12) / 2.0 +
           dphi1 * t28 * (t4 * t59 * 2.0 - t20 * t30 * 2.0) / 2.0;
  t28 = t4 * (1.0 / t60);
  spd[1] = -dphi1 * t60 * t48 * (t52 * t59 - t28 * t30) +
           dphi4 * t60 * t48 * (t52 * (0.0 - t22 * 0.56) + t28 * (t2 * 0.56));
}
