/*
 * leg_function.c
 *
 *  Created on: Dec 10, 2024
 *      Author: YI MING
 */
#include <math.h>
#include "board_lib.h"
#include "bsp_imu.h"
#include "robot_config.h"
#include "balancing_imu_task.h"
#include "dm4310_drv.h"
#include "leg_task.h"
#include "rt_nonfinite.h"
#include "rt_defines.h"

LegPos leftLegPos, rightLegPos;
extern Motor leftJoint[2], rightJoint[2], leftWheel, rightWheel;

void leg_task(void *argument) {
	float legPos[2], legSpd[2];

    while (1) {

    	leg_pos(leftJoint[0].angle, leftJoint[1].angle, legPos);
    	leftLegPos.length = legPos[0];
    	leftLegPos.angle = legPos[1];
    	leg_pos(rightJoint[0].angle, rightJoint[1].angle, legPos);
    	rightLegPos.length = legPos[0];
    	rightLegPos.angle = legPos[1];
    	vTaskDelay(5);
    }
}

#include <math.h>

/* Function Declarations */
static double rt_atan2d_snf(double u0, double u1);

/* Function Definitions */
/*
 * Arguments    : double u0
 *                double u1
 * Return Type  : double
 */
static double rt_atan2d_snf(double u0, double u1)
{
  double y;
  if (rtIsNaN(u0) || rtIsNaN(u1)) {
    y = rtNaN;
  } else if (rtIsInf(u0) && rtIsInf(u1)) {
    int i;
    int i1;
    if (u0 > 0.0) {
      i = 1;
    } else {
      i = -1;
    }
    if (u1 > 0.0) {
      i1 = 1;
    } else {
      i1 = -1;
    }
    y = atan2(i, i1);
  } else if (u1 == 0.0) {
    if (u0 > 0.0) {
      y = RT_PI / 2.0;
    } else if (u0 < 0.0) {
      y = -(RT_PI / 2.0);
    } else {
      y = 0.0;
    }
  } else {
    y = atan2(u0, u1);
  }
  return y;
}

void leg_pos(float phi1, float phi4, float pos[2])
{
	float a;
	float b_a;
	float t14;
	float t15;
	float t2;
	float t3;
	float t4;
	float t5;
	float t6;
	float t8;
  /*     This function was generated by the Symbolic Math Toolbox version 24.1.
   */
  /*     10-Dec-2024 12:58:30 */
  t2 = cos(phi1);
  t3 = cos(phi4);
  t4 = sin(phi1);
  t5 = sin(phi4);
  t6 = t2 * 0.15;
  t8 = t4 * 0.15;
  t14 = t4 * 0.084;
  t15 = t5 * 0.084;
  t5 = t8 - t5 * 0.15;
  a = (t3 * 0.15 - t6) + 0.15;
  b_a = t14 - t15;
  t4 = (t3 * 0.084 - t2 * 0.084) + 0.084;
  t5 = t5 * t5 + a * a;
  t4 = atan(1.0 / (t4 + t5) *
            ((t15 - t14) + sqrt((b_a * b_a + t4 * t4) - t5 * t5))) *
       2.0;
  t5 = t8 + sin(t4) * 0.28;
  t4 = (t6 + cos(t4) * 0.28) - 0.075;
  pos[0] = sqrt(t5 * t5 + t4 * t4);
  pos[1] = rt_atan2d_snf(t5, t4);
}
