/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: lqr_k.c
 *
 * MATLAB Coder version            : 24.1
 * C/C++ source code generated on  : 20-Jul-2024 15:18:13
 */

/* Include Files */
#include "lqr_k.h"
#include "rt_nonfinite.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Declarations */
static double rt_powd_snf(double u0, double u1);

/* Function Definitions */
/*
 * Arguments    : double u0
 *                double u1
 * Return Type  : double
 */
static double rt_powd_snf(double u0, double u1)
{
  double y;
  if (rtIsNaN(u0) || rtIsNaN(u1)) {
    y = rtNaN;
  } else {
    double d;
    double d1;
    d = fabs(u0);
    d1 = fabs(u1);
    if (rtIsInf(u1)) {
      if (d == 1.0) {
        y = 1.0;
      } else if (d > 1.0) {
        if (u1 > 0.0) {
          y = rtInf;
        } else {
          y = 0.0;
        }
      } else if (u1 > 0.0) {
        y = 0.0;
      } else {
        y = rtInf;
      }
    } else if (d1 == 0.0) {
      y = 1.0;
    } else if (d1 == 1.0) {
      if (u1 > 0.0) {
        y = u0;
      } else {
        y = 1.0 / u0;
      }
    } else if (u1 == 2.0) {
      y = u0 * u0;
    } else if ((u1 == 0.5) && (u0 >= 0.0)) {
      y = sqrt(u0);
    } else if ((u0 < 0.0) && (u1 > floor(u1))) {
      y = rtNaN;
    } else {
      y = pow(u0, u1);
    }
  }
  return y;
}

/*
 * LQR_K
 *     K = LQR_K(L0)
 *
 * Arguments    : double L0
 *                double K[12]
 * Return Type  : void
 */
void lqr_k(double L0, double K[12])
{
  double t2;
  double t3;
  /*     This function was generated by the Symbolic Math Toolbox version 24.1.
   */
  /*     30-Dec-2024 15:43:33 */
  t2 = L0 * L0;
  t3 = rt_powd_snf(L0, 3.0);
  K[0] = ((L0 * -74.704676249924631 + t2 * 114.679396699006) -
          t3 * 88.071408525456931) -
         3.0844617208844949;
  K[1] = ((L0 * 41.378327515384981 - t2 * 179.019262117011) +
          t3 * 198.52859704266069) +
         10.64534509867825;
  K[2] = ((L0 * -5.7150775146694084 - t2 * 4.6924826966187121) +
          t3 * 3.937089016074343) -
         0.44227046916064011;
  K[3] = ((L0 * 3.07671171940847 - t2 * 9.1089198456014575) +
          t3 * 8.7743900945584556) +
         1.8669400244328089;
  K[4] = ((L0 * -16.133876307428569 + t2 * 31.591170371787531) -
          t3 * 22.814797264812011) -
         1.722341026550597;
  K[5] = ((L0 * -17.781781453472171 + t2 * 0.7546979661348352) +
          t3 * 20.45416838858192) +
         9.6983979901027464;
  K[6] = ((L0 * -8.3122623717867246 + t2 * 8.1448660108167772) -
          t3 * 1.284530239861128) -
         2.285202031214042;
  K[7] = ((L0 * -25.34414941141549 + t2 * 37.047364842265218) -
          t3 * 22.81176508995485) +
         9.1734147308185552;
  K[8] = ((L0 * -17.39879149350233 + t2 * 15.67224062236915) -
          t3 * 1.669626539375608) +
         7.6488872383659254;
  K[9] = ((L0 * 58.88363268736898 - t2 * 128.62508351846549) +
          t3 * 105.25398045576139) +
         2.4222796090077838;
  K[10] = ((L0 * -5.2591758896931839 + t2 * 8.5723608467353039) -
           t3 * 6.1017751177483186) +
          1.8921613654742759;
  K[11] = ((L0 * 14.75422674199698 - t2 * 33.807567802695807) +
           t3 * 29.120329802301889) -
          0.24831442427020509;
}













/*
 * File trailer for lqr_k.c
 *
 * [EOF]
 */
