/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: lqr_k.c
 *
 * MATLAB Coder version            : 24.1
 * C/C++ source code generated on  : 20-Jul-2024 15:18:13
 */

/* Include Files */
#include "lqr_k.h"
#include "rt_nonfinite.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Declarations */
static double rt_powd_snf(double u0, double u1);

/* Function Definitions */
/*
 * Arguments    : double u0
 *                double u1
 * Return Type  : double
 */
static double rt_powd_snf(double u0, double u1)
{
  double y;
  if (rtIsNaN(u0) || rtIsNaN(u1)) {
    y = rtNaN;
  } else {
    double d;
    double d1;
    d = fabs(u0);
    d1 = fabs(u1);
    if (rtIsInf(u1)) {
      if (d == 1.0) {
        y = 1.0;
      } else if (d > 1.0) {
        if (u1 > 0.0) {
          y = rtInf;
        } else {
          y = 0.0;
        }
      } else if (u1 > 0.0) {
        y = 0.0;
      } else {
        y = rtInf;
      }
    } else if (d1 == 0.0) {
      y = 1.0;
    } else if (d1 == 1.0) {
      if (u1 > 0.0) {
        y = u0;
      } else {
        y = 1.0 / u0;
      }
    } else if (u1 == 2.0) {
      y = u0 * u0;
    } else if ((u1 == 0.5) && (u0 >= 0.0)) {
      y = sqrt(u0);
    } else if ((u0 < 0.0) && (u1 > floor(u1))) {
      y = rtNaN;
    } else {
      y = pow(u0, u1);
    }
  }
  return y;
}

/*
 * LQR_K
 *     K = LQR_K(L0)
 *
 * Arguments    : double L0
 *                double K[12]
 * Return Type  : void
 */
void lqr_k(double L0, double K[12])
{
  double t2;
  double t3;
  /*     This function was generated by the Symbolic Math Toolbox version 24.1.
   */
  /*     20-Jan-2025 20:04:51 */
  t2 = L0 * L0;
  t3 = rt_powd_snf(L0, 3.0);
  K[0] = ((L0 * -77.059556997297051 + t2 * 111.5552377355792) -
          t3 * 73.165516553153338) -
         1.1367748333943939;
  K[1] = ((L0 * 99.499527241542651 - t2 * 413.1574717827836) +
          t3 * 459.29972576741221) +
         12.87055264825104;
  K[2] = ((L0 * -5.6999487081124647 - t2 * 5.9160931855778669) +
          t3 * 7.5547069750677549) -
         0.14647617265642621;
  K[3] = ((L0 * 8.3860629999215828 - t2 * 30.020873705493059) +
          t3 * 31.08754882547812) +
         2.6663994573011478;
  K[4] = ((L0 * -3.85074992113103 + t2 * 7.8268145392221724) -
          t3 * 5.6978296853116861) -
         0.17424654155400821;
  K[5] = ((L0 * -5.0705203808663519 - t2 * 3.6224588196068881) +
          t3 * 12.18551490346063) +
         2.9096718458800148;
  K[6] = ((L0 * -13.54742208296979 + t2 * 26.291981313854571) -
          t3 * 18.5918740337479) -
         0.69702056722916783;
  K[7] = ((L0 * -20.557409911914629 - t2 * 4.9210945831364734) +
          t3 * 34.734756042628717) +
         10.789409352810649;
  K[8] = ((L0 * -46.909927385963393 - t2 * 25.358146071550369) +
          t3 * 100.1485764807163) +
         26.288736208393988;
  K[9] = ((L0 * 357.40500143511571 - t2 * 738.817396892595) +
          t3 * 550.52189121689855) +
         12.024553099909269;
  K[10] = ((L0 * -6.5864720400691024 + t2 * 6.7020261665703593) -
           t3 * 1.7118397956651039) +
          2.7752902747056059;
  K[11] = ((L0 * 26.666046129302881 - t2 * 51.868887543405087) +
           t3 * 36.784216439852962) -
          0.1462240710092782;
}















/*
 * File trailer for lqr_k.c
 *
 * [EOF]
 */
