/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: lqr_k.c
 *
 * MATLAB Coder version            : 24.1
 * C/C++ source code generated on  : 20-Jul-2024 15:18:13
 */

/* Include Files */
#include "lqr_k.h"
#include "rt_nonfinite.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Declarations */
static double rt_powd_snf(double u0, double u1);

/* Function Definitions */
/*
 * Arguments    : double u0
 *                double u1
 * Return Type  : double
 */
static double rt_powd_snf(double u0, double u1)
{
  double y;
  if (rtIsNaN(u0) || rtIsNaN(u1)) {
    y = rtNaN;
  } else {
    double d;
    double d1;
    d = fabs(u0);
    d1 = fabs(u1);
    if (rtIsInf(u1)) {
      if (d == 1.0) {
        y = 1.0;
      } else if (d > 1.0) {
        if (u1 > 0.0) {
          y = rtInf;
        } else {
          y = 0.0;
        }
      } else if (u1 > 0.0) {
        y = 0.0;
      } else {
        y = rtInf;
      }
    } else if (d1 == 0.0) {
      y = 1.0;
    } else if (d1 == 1.0) {
      if (u1 > 0.0) {
        y = u0;
      } else {
        y = 1.0 / u0;
      }
    } else if (u1 == 2.0) {
      y = u0 * u0;
    } else if ((u1 == 0.5) && (u0 >= 0.0)) {
      y = sqrt(u0);
    } else if ((u0 < 0.0) && (u1 > floor(u1))) {
      y = rtNaN;
    } else {
      y = pow(u0, u1);
    }
  }
  return y;
}

/*
 * LQR_K
 *     K = LQR_K(L0)
 *
 * Arguments    : double L0
 *                double K[12]
 * Return Type  : void
 */
void lqr_k(double L0, double K[12])
{
  double t2;
  double t3;
  /*     This function was generated by the Symbolic Math Toolbox version 24.1.
   */
  /*     27-Mar-2025 15:47:56 */
  t2 = L0 * L0;
  t3 = rt_powd_snf(L0, 3.0);
  K[0] = ((L0 * -111.2636797315462 + t2 * 152.304708543741) -
          t3 * 102.4115156875481) -
         3.392977531391022;
  K[1] = ((L0 * 16.585228407336992 - t2 * 125.8422403886369) +
          t3 * 136.03213567418859) +
         25.104076583610841;
  K[2] = ((L0 * -10.886531407632621 - t2 * 7.14400745502269) +
          t3 * 6.6250385380010242) -
         0.028828275753677478;
  K[3] = ((L0 * 12.388690448938871 - t2 * 27.86029678421086) +
          t3 * 22.178267654249819) +
         1.893268652994943;
  K[4] = ((L0 * -6.9082789864928467 + t2 * 15.322867139408361) -
          t3 * 12.00803696248285) -
         0.638759643984115;
  K[5] = ((L0 * -14.221269994873589 + t2 * 19.93820443421831) -
          t3 * 10.49141938543517) +
         4.6571299097611742;
  K[6] = ((L0 * -23.447004027072381 + t2 * 49.633750108302323) -
          t3 * 38.351892580992221) -
         2.4376685680659009;
  K[7] = ((L0 * -52.798198256027632 + t2 * 79.057585669721959) -
          t3 * 45.635530718133751) +
         16.798643875840948;
  K[8] = ((L0 * -152.8358930027679 + t2 * 220.38180490104219) -
          t3 * 121.29538246494531) +
         49.984161410688827;
  K[9] = ((L0 * 469.71432234398929 - t2 * 1052.053022986247) +
          t3 * 832.09586618133233) +
         31.170430459968792;
  K[10] = ((L0 * -14.97834911748544 + t2 * 22.9926016136362) -
           t3 * 14.13530653591463) +
          5.2206271855558546;
  K[11] = ((L0 * 44.362184378104978 - t2 * 95.332020563686484) +
           t3 * 73.6109240164324) -
          0.28094916222058819;
}

















/*
 * File trailer for lqr_k.c
 *
 * [EOF]
 */
