/*
 * hud_roburt.h
 *
 *  Created on: May 26, 2024
 *      Author: wx
 */

#ifndef ROBOT_CONFIG_HUD_ROBURT_H_
#define ROBOT_CONFIG_HUD_ROBURT_H_
#include "hud_constants.h"

//in pixels
//#define CUSTOM_CROSSHAIR
//assuming 1920x1080 screen
#define CROSSHAIR_RIGHT_OFFSET	0
#define CROSSHAIR_UP_OFFSET		-40
#define CROSSHAIR_THICKNESS	2
#define CROSSHAIR_COLOUR	GRAPHIC_COLOUR_WHITE
#define CROSSHAIR_LENGTH_X	20
#define CROSSHAIR_CENTER_X	(960 + CROSSHAIR_RIGHT_OFFSET)
#define CROSSHAIR_CENTER_Y	(540 + CROSSHAIR_UP_OFFSET)
#define CROSSHAIR_LENGTH_Y CROSSHAIR_LENGTH_X
#define CROSSHAIR_START_X	(CROSSHAIR_CENTER_X - (CROSSHAIR_LENGTH_X/2))
#define CROSSHAIR_END_X		(CROSSHAIR_START_X + CROSSHAIR_LENGTH_X)
#define CROSSHAIR_START_Y	(CROSSHAIR_CENTER_Y - (CROSSHAIR_LENGTH_Y/2))
#define CROSSHAIR_END_Y		(CROSSHAIR_START_Y + CROSSHAIR_LENGTH_Y)

#define CROSSHAIR_TWO_COLOUR
#define CROSSHAIR_SHADOW_THICKNESS		4
#define CROSSHAIR_SHADOW_COLOUR	GRAPHIC_COLOUR_BLACK
#define CROSSHAIR_DOT_COLOUR	GRAPHIC_COLOUR_PURPLISH_RED
#define CROSSHAIR_DOT_WIDTH		5


#endif /* ROBOT_CONFIG_HUD_ROBURT_H_ */
